### ISSUE TITLE
Advice on executing from non-python environment

### ISSUE THREAD

**Issue by mhkeller** [0x0L/pgeon#33]
I have a question that is likely out of scope for this project but wanted to run it by you. I want to execute queries against a postgres db and have the result written to an arrow file, which seems like exactly what you've done. The catch is I want to do this from within an Electron or Tauri – so not a python environment. 

A very hacky solution would be to have a basic python file and call it from the command line with arguments for a connection string and SQL and call it from the main system, but that seems like a lot of overhead. 

If you have any advice on using this library or some other approach that you may be aware of in this space, I would greatly appreciate it.

**Comment by rdbisme** [comment]
Hello @mhkeller. I'm not an expert in node / electron world, but since `pgeon` is mainly a compiled library, maybe you could try to use something like [node-ffi](https://github.com/node-ffi/node-ffi) or [electron-node-ffi](https://github.com/raviSussol/electron-node-ffi). Like this you can call directly the dynamic library from your node code, without the need of interacting with Python in any way. (Basically the same we do with our Python bindings)?

**Comment by mhkeller** [comment]
Sorry I missed your reply. Thanks for the links. I ended up with a slightly different setup using parquet files but I’ll keep this as an option to investigate if arrow ends up being better.
