### ISSUE TITLE
Make pgeon fully pip installable

### ISSUE THREAD

**Issue by 0x0L** [0x0L/pgeon#8]
On the current [pip_only](https://github.com/0x0L/pgeon/tree/pip_only) branch, start from a minimal environment.yml without `pyarrow`

```yaml
name: pgeon-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - git
  - libpq
  - python=3.11
```

On MacOS, installing with `pip install .` works ok given that we actually `import pyarrow` before `import _pgeon`, see [pgeon.py](https://github.com/0x0L/pgeon/blob/pip_only/python/pgeon.py)

In the dev container though, the result is 

```
>>> import pgeon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.11/site-packages/pgeon.py", line 5, in <module>
    from _pgeon import copy_query
ImportError: /opt/conda/lib/python3.11/site-packages/_pgeon.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZNK5arrow8DataType18ComputeFingerprintB5cxx11Ev
```

`pip uninstall pyarrow numpy` and `micromamba install -c conda-forge pyarrow` without reinstalling `pgeon` fixes the issue

I' suspect an issue with pyarrow pypi linux wheels but TBH I just don't know what's going on

**Comment by rdbisme** [comment]
The reason why it happens, I think it's related to the fact that you're installing `pyarrow` in the dev container from `conda`. That `pyarrow` is built against conda compiler, that is not manylinux compatible on Linux. So when you do `pip install`, it will use the `build requires` in the `pyproject.toml`, that is `pyarrow` built against manylinux, but when you run it, it will link against `pyarrow` from conda, that has different symbols. 

That's why I was working on #7. You need to link against `arrow` built on `manylinux` to make it work.

**Comment by 0x0L** [comment]
In what I described there's just one pyarrow from pip (two since the build is isolated)

**Comment by rdbisme** [comment]
Don't you have the conda one in the `environment.yml`?

Maybe I'm misunderstanding the problem, but when you do ` pip install .`, it will first build in an isolated environment using `pyarrow` from `pypi` (i.e. the one compiled against `manylinux`). `_pgeon` will be linked against that one. 

When you do the runtime `import`, the `pyarrow` available is the one from `conda`, then the dynamic linking will use the conda one, that has different symbols, and it will fail. No?

**Comment by 0x0L** [comment]
No I don't use conda in that case, see the environment I posted

**Comment by 0x0L** [comment]
CXX ABI issues
